# golangci-lint configuration for repo-sync
# Compatible with golangci-lint v1.64.x

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Official Go static analyzer
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  staticcheck:
    checks: ["all"]

  gosimple:
    checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - .github
